apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: hotel
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Daemon        Off
        Log_Level     info
        Parsers_File  /fluent-bit/etc/parsers.conf

    [INPUT]
        Name          tail
        Path          /usr/local/apache2/logs/access.log
        Parser        apache
        Tag           httpd_logs
        Mem_Buf_Limit 5MB

    [FILTER]
        Name          record_modifier
        Match         httpd_logs
        Record        service apache_web

    [OUTPUT]
        Name          splunk
        Match         httpd_logs
        Host          splunk-service.svc.cluster.local
        Port          8088
        Splunk_Token  ${SPLUNK_TOKEN}
        Splunk_Send_Raw On
        Format        json

  parsers.conf: |
    [PARSER]
        Name   apache
        Format regex
        Regex  ^(?<log_level>[A-Z]+)\s+(?<log_source>[^\:]+):\s+(?<log_message>.+)$
        Time_Key log_time
        Time_Format %Y-%m-%dT%H:%M:%S
