apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-logging
  labels:
    app: hotel-logging
  namespace: hotel
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hotel-logging
  template:
    metadata:
      labels:
        app: hotel-logging
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
        - name: hotel-logging-server
          image: docker.io/hotel/httpd-custom-hotel-logging:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: logs
              mountPath: /usr/local/apache2/logs
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

        - name: fluent-bit-logger
          image: docker.io/hotel/fluent-custom-logger:latest
          env:
            - name: SPLUNK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: splunk-secret
                  key: SPLUNK_TOKEN
          volumeMounts:
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
              subPath: fluent-bit.conf
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
              subPath: parsers.conf
            - name: logs
              mountPath: /usr/local/apache2/logs
          livenessProbe:
            exec:
              command: ["/bin/sh", "-c", "pgrep fluent-bit"]
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "pgrep fluent-bit"]
            initialDelaySeconds: 5
            periodSeconds: 10

      volumes:
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
        - name: logs
          emptyDir: {}

