apiVersion: v1
kind: Service
metadata:
  name: hotel-logging-service
  namespace: hotel
spec:
  selector:
    app: hotel-logging
  ports:
    - name: http
      protocol: TCP
      port: 80        
      targetPort: 80  
      nodePort: 30080 
  type: NodePort
