{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "logging-app.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "logging-app.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
